sudo: false

language: python

python:
  - "3.3"
  - "3.4"
  - "3.5.0"
  - "3.5.2"
  - "3.6"

install: pip install tox-travis

script: tox

deploy:
  provider: pypi
  user: agronholm
  password:
    secure: Ej78kpDGrmWjt1aNQR9dV9lQpMubaGoYkEXxIyQkhEiiPo8wQsB8ACU9IDma1uiJKkM253Skh85d6QOcNgqiRgj8oGhOWmVfnQArGC8M5fAYqHXTTisdoy6n+nELBw7C3AhxsbQ5/LGpNa+C5nZQ/0vqS9b2Kg7h4cuw/uoJwUqC6BQaqT12QYQh83JcZBBy1LNXP2JOOHghbZXoFV+iapRCFx55Tb9e/YqmUApWN9CVIp/y0maFHwJlNo9lVyFOl3a3wKjoA0amIBMb/aYXzNXQZyiz5/OKMtRBYKbYkYWnoDY1e1t3+hZWeL5MMws7yFPGmRd4zSvudL9Ytnt21Vk3mTt2nMz5I48wBHeaq5a0W18VEr8ozTdMl0m9zSyq1WYdGguk5SYZ6GEu5/tkJ9k+WMjAj3Xu8nkf8we8iOWvWX5UllAtodnzglu+2IA8HgP+zV47gQeryVx9dyP9xj5pvckIO7C6RDltcjHVK2F1lsSS0uV30ky0tU8V6/UIbDNDRBJZNjPIGRaB7GHyCQoxrEc4CvWheQhJxGN1gRYqd+F0QjriBG5jMzPPGIENh66Z5VZl/GS4zDpDj2aAhp4NPuP7wANluEOuZSv3q6wfAJan5R8mmOdyNQ2xOoMHif3xDKLLORnzmopjloGg4bvP1whFbYFlYEQ0tZkiSiU=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "3.6"
    repo: agronholm/sphinx-autodoc-typehints
